import fs from 'node:fs';
import { pathToFileURL } from 'node:url';

const requiredCounts = ['profiles', 'purchases', 'purchase_payments', 'payroll_runs', 'payroll_items', 'salary_advances', 'payroll_advance_allocations'];
const requiredTotals = ['expenses_total', 'supplier_payments_total', 'paid_salary_total', 'active_payroll_expenses_total', 'open_salary_advances_total'];
const plain = value => value !== null && typeof value === 'object' && !Array.isArray(value);

export function validateManifest(value) {
  if (!plain(value) || value.format_version !== 1 || !plain(value.manifest)) throw Error('Missing recovery manifest format');
  const manifest = value.manifest;
  if (manifest.app_version !== '0.38.0' || manifest.latest_migration !== 38) throw Error('Expected v0.38 / migration 38');
  for (const key of ['critical_counts', 'integrity', 'financial_totals']) {
    if (!plain(manifest[key]) || !Object.keys(manifest[key]).length) throw Error(`Missing ${key}`);
    for (const n of Object.values(manifest[key])) if (typeof n !== 'number' || !Number.isFinite(n) || n < 0) throw Error(`Invalid ${key} value`);
  }
  for (const key of requiredCounts) if (!Object.hasOwn(manifest.critical_counts, key)) throw Error(`Missing critical count: ${key}`);
  for (const key of requiredTotals) if (!Object.hasOwn(manifest.financial_totals, key)) throw Error(`Missing financial total: ${key}`);
  if (!plain(value.table_counts) || !Object.keys(value.table_counts).length) throw Error('Missing public table counts');
  for (const n of Object.values(value.table_counts)) if (!Number.isSafeInteger(n) || n < 0) throw Error('Invalid public table count');
  if (!Number.isSafeInteger(value.auth_user_count) || value.auth_user_count < 1) throw Error('Missing Auth users');
  if (!Array.isArray(value.migrations) || !value.migrations.length) throw Error('Missing migration history');
  if (value.migrations.some(row => !plain(row) || !/^\d{14}$/.test(row.version || '') || typeof row.name !== 'string')) throw Error('Invalid migration history');
  if (!Array.isArray(value.public_security) || !value.public_security.length) throw Error('Missing table security evidence');
  if (!Array.isArray(value.raw_material_stock)) throw Error('Missing material balances');
  if (value.raw_material_stock.some(row => !plain(row) || typeof row.id !== 'string' || typeof row.quantity !== 'number' || !Number.isFinite(row.quantity) || row.quantity < 0)) throw Error('Invalid material balances');
  if (!plain(value.guards) || value.guards.operations_enabled !== false || !['production', 'staging'].includes(value.guards.environment_mode)) throw Error('Live operations must remain disabled');
  if (value.guards.environment_mode === 'production' && value.guards.production_lock !== true) throw Error('Production Lock must remain ON');
  if (manifest.integrity.negative_stock_count !== 0 || manifest.integrity.mobile_money_conflict_count !== 0 || manifest.integrity.active_owner_count < 1) throw Error('Source integrity checks need review');
  if (value.public_security.some(table => !plain(table) || table.rls !== true)) throw Error('Public table RLS needs review');
  if (value.public_security.map(row => row.table).sort().join('|') !== Object.keys(value.table_counts).sort().join('|')) throw Error('Public table security coverage mismatch');
  for (const [table, count] of Object.entries(manifest.critical_counts)) if (value.table_counts[table] !== count) throw Error('Critical count does not match table counts');
  return value;
}

function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (plain(value)) return Object.fromEntries(Object.keys(value).sort().map(key => [key, canonical(value[key])]));
  return value;
}

export function compareManifests(source, restored) {
  validateManifest(source); validateManifest(restored);
  // Only the timestamp generated by this read is ignored. No financial or integrity evidence is removed.
  const normalized = value => {
    const copy = structuredClone(value);
    delete copy.manifest.generated_at;
    return canonical(copy);
  };
  const expected = normalized(source), actual = normalized(restored);
  const mismatches = [];
  for (const key of new Set([...Object.keys(expected), ...Object.keys(actual)])) {
    if (JSON.stringify(expected[key]) !== JSON.stringify(actual[key])) mismatches.push(key);
  }
  if (mismatches.length) throw Error(`Recovery comparison failed: ${mismatches.join(', ')}`);
  return true;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    if (process.argv.length !== 4) throw Error('Usage: node manifest.mjs <source.json> <restored.json>');
    if (process.argv[2] === 'validate') {
      validateManifest(JSON.parse(fs.readFileSync(process.argv[3], 'utf8')));
      console.log('Source manifest validated. No restore was performed.');
    } else {
      compareManifests(JSON.parse(fs.readFileSync(process.argv[2], 'utf8')), JSON.parse(fs.readFileSync(process.argv[3], 'utf8')));
      console.log('PASS: recovery counts, totals, balances, migration history, RLS and launch guards match.');
    }
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
