'use client';

import { useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Sidebar from "@/components/Sidebar";
import { createClient } from "@/lib/supabase/client";
import { CartLine, subtotal, discountAmount, grandTotal, changeDue } from "@/lib/pos";
import { ugx } from "@/lib/costing";

type PaymentMethod="cash"|"mtn_momo"|"airtel_money"|"bank"|"customer_credit"|"split";
type SplitState={cash:number;mtn_momo:number;airtel_money:number;bank:number;mtn_ref:string;airtel_ref:string;bank_ref:string};

export default function PosTerminal({products,openShift,customers,live}:{products:any[];openShift:any|null;customers:any[];live:boolean}){
  const router=useRouter();
  const [cart,setCart]=useState<CartLine[]>([]);const [discountType,setDiscountType]=useState<"amount"|"percent">("amount");const [discountValue,setDiscountValue]=useState(0);
  const [promoCode,setPromoCode]=useState("");const [promoDiscount,setPromoDiscount]=useState(0);
  const [paymentMethod,setPaymentMethod]=useState<PaymentMethod>("cash");const [received,setReceived]=useState(0);const [reference,setReference]=useState("");const [customerId,setCustomerId]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  const [split,setSplit]=useState<SplitState>({cash:0,mtn_momo:0,airtel_money:0,bank:0,mtn_ref:"",airtel_ref:"",bank_ref:""});
  const requestId=useRef<string>(crypto.randomUUID());
  const sub=useMemo(()=>subtotal(cart),[cart]);const manualDisc=useMemo(()=>discountAmount(sub,discountType,discountValue),[sub,discountType,discountValue]);const disc=Math.min(sub,manualDisc+promoDiscount);const total=useMemo(()=>grandTotal(sub,disc),[sub,disc]);const change=paymentMethod==="cash"?changeDue(received,total):0;const selectedCustomer=customers.find((c:any)=>(c.id??c.customer_id)===customerId);
  const splitTotal=split.cash+split.mtn_momo+split.airtel_money+split.bank;

  function addProduct(p:any){setCart(prev=>{const found=prev.find(x=>x.productId===p.id);if(found)return prev.map(x=>x.productId===p.id?{...x,quantity:x.quantity+1}:x);return [...prev,{productId:p.id,name:p.name,unitPrice:Number(p.selling_price),quantity:1}]});}
  function updateQty(id:string,delta:number){setCart(prev=>prev.map(x=>x.productId===id?{...x,quantity:Math.max(0,x.quantity+delta)}:x).filter(x=>x.quantity>0));}
  async function applyPromo(){if(!promoCode.trim()){setPromoDiscount(0);return;}if(manualDisc>0){setMessage("Remove the manual discount before applying a promotion code. Promotions and manual discounts cannot be stacked.");return;}if(!cart.length){setMessage("Add products before applying a promotion code.");return;}if(!live){setMessage("Demo mode: promo validation simulated.");return;}try{const supabase=createClient();const {data,error}=await supabase.rpc("quote_promotion",{p_code:promoCode,p_items:cart.map(x=>({product_id:x.productId,quantity:x.quantity}))});if(error)throw error;const d=Number((data as any)?.discount||0);setPromoDiscount(d);setMessage(d>0?`Promo applied: ${ugx(d)}`:"Promotion produced no discount for this cart.");}catch(e){setPromoDiscount(0);setMessage(e instanceof Error?e.message:"Could not validate promo.");}}

  function payments(){if(paymentMethod==="split")return [{method:"cash",amount:split.cash,reference:null},{method:"mtn_momo",amount:split.mtn_momo,reference:split.mtn_ref},{method:"airtel_money",amount:split.airtel_money,reference:split.airtel_ref},{method:"bank",amount:split.bank,reference:split.bank_ref}].filter(x=>x.amount>0);return [{method:paymentMethod,amount:total,reference:paymentMethod==="cash"?null:reference.trim()}];}

  async function submit(hold:boolean){
    if(!cart.length){setMessage("Add at least one product.");return;}if(!openShift){setMessage("Start a cashier shift before creating sales.");return;}if(promoDiscount>0&&manualDisc>0){setMessage("Remove either the manual discount or the promotion code. Discounts cannot be stacked.");return;}
    if(!hold&&paymentMethod==="cash"&&received<total){setMessage("Cash received is less than the total.");return;}
    if(!hold&&["mtn_momo","airtel_money","bank"].includes(paymentMethod)&&!reference.trim()){setMessage("Enter the payment reference.");return;}
    if(!hold&&paymentMethod==="split"){if(Math.round(splitTotal)!==Math.round(total)){setMessage(`Split payments must equal ${ugx(total)}. Current split: ${ugx(splitTotal)}.`);return;}if(split.mtn_momo>0&&!split.mtn_ref.trim()){setMessage("Enter the MTN reference.");return;}if(split.airtel_money>0&&!split.airtel_ref.trim()){setMessage("Enter the Airtel reference.");return;}if(split.bank>0&&!split.bank_ref.trim()){setMessage("Enter the bank reference.");return;}}
    if(!hold&&paymentMethod==="customer_credit"&&!customerId){setMessage("Select a registered customer for a credit sale.");return;}if(!hold&&paymentMethod==="customer_credit"&&!selectedCustomer?.credit_enabled){setMessage("Credit is not enabled for this customer.");return;}if(!hold&&paymentMethod==="customer_credit"&&Number(selectedCustomer?.available_credit??0)<total){setMessage("This sale would exceed the customer’s available credit.");return;}
    if(!live){setMessage(hold?"Demo sale held.":"Demo sale completed. No cloud transaction was created.");return;}
    setBusy(true);setMessage("");try{const supabase=createClient();let data:any,error:any;if(!hold&&paymentMethod==="customer_credit"){const result=await supabase.rpc("complete_credit_sale",{p_items:cart.map(x=>({product_id:x.productId,quantity:x.quantity})),p_discount:disc,p_notes:null,p_client_request_id:requestId.current,p_customer_id:customerId});data=result.data;error=result.error;}else{const result=await supabase.rpc("complete_sale_with_customer",{p_items:cart.map(x=>({product_id:x.productId,quantity:x.quantity})),p_discount:disc,p_payments:hold?[]:payments(),p_notes:promoCode?`Promo ${promoCode}`:null,p_hold:hold,p_client_request_id:requestId.current,p_customer_id:customerId||null});data=result.data;error=result.error;}if(error)throw error;setMessage(`${hold?"Sale held":"Sale completed"} • Reference ${data}`);if(!hold){setCart([]);setDiscountValue(0);setPromoCode("");setPromoDiscount(0);setReceived(0);setReference("");setCustomerId("");setSplit({cash:0,mtn_momo:0,airtel_money:0,bank:0,mtn_ref:"",airtel_ref:"",bank_ref:""});requestId.current=crypto.randomUUID();}router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not complete sale.");}finally{setBusy(false);}
  }

  return <div className="shell"><Sidebar/><main className="main"><div className="pagehead"><div><h1>Cashier POS</h1><p>Fast selling with controlled discounts, promo codes, customer credit and split tender.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><span className={openShift?"badge green":"badge red"}>{openShift?"Shift Open":"No Open Shift"}</span><button className="btn secondary" disabled={busy} onClick={()=>submit(true)}>Hold Sale</button><button className="btn secondary" onClick={()=>setCart([])}>Clear Cart</button></div></div>
  {message&&<div className="hero" style={{padding:14,marginBottom:14}}><b>{message}</b></div>}{!openShift&&<div className="hero"><h2>Cashier shift required</h2><p>Open a cashier shift before selling. <a href="/shifts"><b>Go to Cashier Shifts</b></a>.</p></div>}
  <div className="grid2"><section><div className="card"><h3>Products</h3><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:10}}>{products.map((p:any)=><button key={p.id} onClick={()=>addProduct(p)} className="btn secondary" style={{minHeight:95,textAlign:"left"}}><div style={{fontWeight:900}}>{p.name}</div><div style={{fontSize:11,color:"var(--muted)",marginTop:4}}>{p.category_name}</div><div style={{fontSize:12,color:"var(--muted)",marginTop:4}}>{ugx(Number(p.selling_price))}</div></button>)}</div></div></section>
  <section><div className="card"><h3>Current Sale</h3>{cart.length===0?<p style={{color:"var(--muted)"}}>Tap a product to start the sale.</p>:<div className="tablewrap"><table style={{minWidth:0}}><thead><tr><th>Item</th><th>Qty</th><th>Total</th></tr></thead><tbody>{cart.map(line=><tr key={line.productId}><td><b>{line.name}</b><br/><small>{ugx(line.unitPrice)} each</small></td><td><div style={{display:"flex",gap:6,alignItems:"center"}}><button className="btn secondary" onClick={()=>updateQty(line.productId,-1)}>-</button><b>{line.quantity}</b><button className="btn secondary" onClick={()=>updateQty(line.productId,1)}>+</button></div></td><td><b>{ugx(line.unitPrice*line.quantity)}</b></td></tr>)}</tbody></table></div>}
  <div className="grid2"><div className="field"><label>Discount type</label><select value={discountType} onChange={e=>{setDiscountType(e.target.value as any);setPromoDiscount(0);}}><option value="amount">Amount</option><option value="percent">Percent</option></select></div><div className="field"><label>Discount value</label><input type="number" min="0" value={discountValue} onChange={e=>{setDiscountValue(Number(e.target.value));setPromoDiscount(0);}}/></div></div><div style={{display:"flex",gap:8}}><div className="field" style={{flex:1}}><label>Promo code</label><input value={promoCode} onChange={e=>{setPromoCode(e.target.value.toUpperCase());setPromoDiscount(0);}}/></div><button className="btn secondary" style={{alignSelf:"end",marginBottom:14}} onClick={applyPromo}>Apply</button></div>
  <p style={{display:"flex",justifyContent:"space-between"}}><span>Subtotal</span><b>{ugx(sub)}</b></p><p style={{display:"flex",justifyContent:"space-between"}}><span>Total discount</span><b>- {ugx(disc)}</b></p><p style={{display:"flex",justifyContent:"space-between",fontSize:22,borderTop:"2px solid var(--brown)",paddingTop:9}}><span><b>Total</b></span><b>{ugx(total)}</b></p>
  <div className="field"><label>Customer</label><select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Walk-in customer</option>{customers.map((c:any)=><option key={c.id??c.customer_id} value={c.id??c.customer_id}>{c.full_name}</option>)}</select></div><div className="field"><label>Payment method</label><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value as PaymentMethod)}><option value="cash">Cash</option><option value="mtn_momo">MTN MoMo</option><option value="airtel_money">Airtel Money</option><option value="bank">Bank</option><option value="split">Split Payment</option><option value="customer_credit">Customer Credit</option></select></div>
  {paymentMethod==="cash"?<><div className="field"><label>Cash received</label><input type="number" min="0" value={received} onChange={e=>setReceived(Number(e.target.value))}/></div><p><b>Change: {ugx(change)}</b></p></>:paymentMethod==="customer_credit"?<div className="hero" style={{padding:12}}><b>Credit Sale</b><p>Available credit: {ugx(Number(selectedCustomer?.available_credit??0))}</p></div>:paymentMethod==="split"?<div className="card" style={{padding:12}}><h4>Split Tender</h4>{(['cash','mtn_momo','airtel_money','bank'] as const).map(k=><div className="grid2" key={k}><div className="field"><label>{k.replaceAll('_',' ')}</label><input type="number" min="0" value={split[k]} onChange={e=>setSplit(v=>({...v,[k]:Number(e.target.value)}))}/></div>{k!=="cash"&&<div className="field"><label>Reference</label><input value={split[`${k==='mtn_momo'?'mtn':k==='airtel_money'?'airtel':'bank'}_ref` as keyof SplitState] as string} onChange={e=>setSplit(v=>({...v,[`${k==='mtn_momo'?'mtn':k==='airtel_money'?'airtel':'bank'}_ref`]:e.target.value}))}/></div>}</div>)}<b>Split total: {ugx(splitTotal)}</b></div>:<div className="field"><label>Payment reference</label><input value={reference} onChange={e=>setReference(e.target.value)}/></div>}
  <button className="btn primary" disabled={busy||!openShift} style={{width:"100%",marginTop:8}} onClick={()=>submit(false)}>{busy?"Posting…":"Complete Sale"}</button></div></section></div></main></div>;
}
